openapi: 3.0.1
info:
  title: IteratorMediatorAPI
  description: API Definition of IteratorMediatorAPI
  version: 1.0.0
servers:
- url: http://localhost:8290/iterator
paths:
  /:
    get:
      responses:
        default:
          description: Default response
